"""Add fcm_token to RemajaPutri

Revision ID: 29f080ade5d5
Revises: adaba11e9043
Create Date: 2025-07-23 12:59:47.684445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f080ade5d5'
down_revision = 'adaba11e9043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['fcm_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
