"""Add roles and answered_by fields

Revision ID: 61aed59f4c67
Revises: b3a59e280202
Create Date: 2025-07-25 11:47:46.347697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61aed59f4c67'
down_revision = 'b3a59e280202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
