"""Add profile image to RemajaPutri

Revision ID: 705762ce3159
Revises: 7bc0779b0190
Create Date: 2025-08-05 13:19:47.499938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705762ce3159'
down_revision = '7bc0779b0190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.drop_column('profile_image_filename')

    # ### end Alembic commands ###
