"""Add dose to DailyLog and schedule to RemajaPutri

Revision ID: 75fc74f53e36
Revises: 9cd1c310de67
Create Date: 2025-08-19 14:45:35.841488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fc74f53e36'
down_revision = '9cd1c310de67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosis', sa.String(length=50), nullable=True))

    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jadwal_ttd', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.drop_column('jadwal_ttd')

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_column('dosis')

    # ### end Alembic commands ###
