"""Add zscore to HealthScreening

Revision ID: 793e6f53673c
Revises: 98fd54dd2f0c
Create Date: 2025-08-19 13:16:56.885317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793e6f53673c'
down_revision = '98fd54dd2f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_screening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi_zscore', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_screening', schema=None) as batch_op:
        batch_op.drop_column('bmi_zscore')

    # ### end Alembic commands ###
