"""Add HealthScreening model

Revision ID: 8d3bb1642e31
Revises: fac57d5c8fd8
Create Date: 2025-08-19 12:38:09.542301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3bb1642e31'
down_revision = 'fac57d5c8fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_screening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_skrining', sa.Date(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('tinggi_badan', sa.Float(), nullable=True),
    sa.Column('imt', sa.Float(), nullable=True),
    sa.Column('kadar_hb', sa.Float(), nullable=True),
    sa.Column('riwayat_haid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['remaja_putri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_screening')
    # ### end Alembic commands ###
