"""Add points column to RemajaPutri model

Revision ID: 93bf7d9ae90b
Revises: fd2ab4890beb
Create Date: 2025-07-21 12:37:05.454477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bf7d9ae90b'
down_revision = 'fd2ab4890beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###
