"""Add birthdate and sex to user

Revision ID: 9cd1c310de67
Revises: 793e6f53673c
Create Date: 2025-08-19 13:18:21.443473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd1c310de67'
down_revision = '793e6f53673c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('jenis_kelamin', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remaja_putri', schema=None) as batch_op:
        batch_op.drop_column('jenis_kelamin')
        batch_op.drop_column('tanggal_lahir')

    # ### end Alembic commands ###
