"""Enhance DailyLog model for detailed TTD tracking

Revision ID: ae6abb6e3dd8
Revises: 705762ce3159
Create Date: 2025-08-19 11:05:09.534306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae6abb6e3dd8'
down_revision = '705762ce3159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('jam_konsumsi', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('efek_samping', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('alasan_lupa', sa.Text(), nullable=True))
        batch_op.drop_column('minum_ttd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minum_ttd', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('alasan_lupa')
        batch_op.drop_column('efek_samping')
        batch_op.drop_column('jam_konsumsi')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
