"""Re-sync answered_by and role columns

Revision ID: dd6c1efd5d37
Revises: 61aed59f4c67
Create Date: 2025-07-25 11:57:15.469046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6c1efd5d37'
down_revision = '61aed59f4c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('answered_by')

    # ### end Alembic commands ###
