"""Add NutritionLog model

Revision ID: fac57d5c8fd8
Revises: ae6abb6e3dd8
Create Date: 2025-08-19 11:38:11.162352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac57d5c8fd8'
down_revision = 'ae6abb6e3dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('karbohidrat', sa.Boolean(), nullable=True),
    sa.Column('lauk_hewani', sa.Boolean(), nullable=True),
    sa.Column('lauk_nabati', sa.Boolean(), nullable=True),
    sa.Column('sayur', sa.Boolean(), nullable=True),
    sa.Column('buah', sa.Boolean(), nullable=True),
    sa.Column('camilan_manis', sa.Integer(), nullable=True),
    sa.Column('minuman_manis', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['remaja_putri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tanggal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition_log')
    # ### end Alembic commands ###
